### ISSUE TITLE
启动letta失败

### ISSUE THREAD

**Issue by masteryumia** [Zao-chen/ZcChat#10]
D:\ai\letta-0.5.5>letta server

Traceback (most recent call last):

File "<frozen runpy>", line 198, in _run_module_as_main

File "<frozen runpy>", line 88, in _run_code

File "C:\Users\浩哲\AppData\Local\Programs\Python\Python312\Scripts\letta.exe\__main__.py", line 4, in <module>

File "D:\ai\letta-0.5.5\letta\__init__.py", line 4, in <module>

from letta.client.client import LocalClient, RESTClient, create_client

File "D:\ai\letta-0.5.5\letta\client\client.py", line 7, in <module>

import letta.utils

File "D:\ai\letta-0.5.5\letta\utils.py", line 21, in <module>

import demjson3 as demjson

ModuleNotFoundError: No module named 'demjson3'D:\ai\letta-0.5.5>import demjson3

'import' is not recognized as an internal or external command,

operable program or batch file.D:\ai\letta-0.5.5>pip install demjson3

Requirement already satisfied: demjson3 in c:\users\浩哲\appdata\local\programs\python\python312\lib\site-packages (3.0.6)
打开letta显示无法找到demjson3 我用pip重新下载却又说我已经有demjson3

**Comment by Zao-chen** [comment]
如果你有对多个环境的话。检查demjson3是否在该Python环境下安装，以及路径是否有问题。或者尝试使用虚拟环境安装。
进一步支持可以去letta仓库下反馈

**Comment by Zao-chen** [comment]
如果你有对多个环境的话。检查demjson3是否在该Python环境下安装，以及路径是否有问题。或者尝试使用虚拟环境安装。
进一步支持可以去letta仓库下反馈
