### ISSUE TITLE
佬救命

### ISSUE THREAD

**Issue by hymint** [Zao-chen/ZcChat#17]
一开始我是用的最新版本letta，但是启动后会有一个报错"GET /v1/tools/composio/apps HTTP/1.1" 400 Bad Request。网页可以正常对话，但是ai的回复没法回到ZNChat的聊天框中，聊天框会显示未知错误
然后我把letta版本退回到0.55,启动letta时启动失败，大佬帮忙看一下
C:\Users\29304\Desktop\letta-0.5.5>letta server
Traceback (most recent call last):
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\functions\functions.py", line 22, in derive_openai_json_schema
    exec(source_code, env)
  File "<string>", line 1, in <module>
NameError: name 'Agent' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Scripts\letta.exe\__main__.py", line 7, in <module>
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 783, in main
    return _main(
           ^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\core.py", line 225, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 1443, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\click\core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\AppData\Local\Programs\Python\Python312\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\cli\cli.py", line 65, in server
    from letta.server.rest_api.app import start_server
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\server\rest_api\app.py", line 48, in <module>
    server = SyncServer(default_interface_factory=lambda: interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\server\server.py", line 256, in __init__
    self.tool_manager.add_base_tools(actor=self.default_user)
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\utils.py", line 544, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\services\tool_manager.py", line 174, in add_base_tools
    self.create_or_update_tool(
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\utils.py", line 544, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\services\tool_manager.py", line 52, in create_or_update_tool
    self.update_tool_by_id(tool.id, ToolUpdate(**update_data), actor)
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\utils.py", line 544, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\services\tool_manager.py", line 126, in update_tool_by_id
    new_schema = derive_openai_json_schema(source_code=pydantic_tool.source_code)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\29304\Desktop\letta-0.5.5\letta\functions\functions.py", line 32, in derive_openai_json_schema
    raise RuntimeError(f"Failed to execute source code: {e}")
RuntimeError: Failed to execute source code: name 'Agent' is not defined

**Comment by Zao-chen** [comment]
letta退版本需要将用户文件夹中的.letta文件删除，因为旧版本无法支持新版本的数据库。
估计letta新版本post格式有变化，下个版本应该会适配。

**Comment by hymint** [comment]
谢谢佬，退版本就解决问题了，请问这个letta和vits可以开机自启动吗，还是必须开机自己开一下他们两个

**Comment by Zao-chen** [comment]
> 谢谢佬，退版本就解决问题了，请问这个letta和vits可以开机自启动吗，还是必须开机自己开一下他们两个

设置里面有一个自启动，可以在开启软件的时候自动启动vits和letta

**Comment by Zao-chen** [comment]
更新了，适配了letta新版本
